# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js book_ms CI

on:
  push:
    branches: [ amqp ]
    paths:
    - 'books_ms/**'
  pull_request:
    branches: [ amqp ]
    paths:
    - 'books_ms/**'

jobs:
  build:
      
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 14.x ]
        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    
    - name: Intall dependencies
      working-directory: books_ms
      run: npm install 
      
    - name: Run build
      working-directory: books_ms
      run: npm run build --if-present
      